[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mykit"
version = "10.0.0b11"

[tool.setuptools.packages.find]
exclude = [
    "_etc*",
    "tests*",
]

[project.scripts]
mykit = "mykit.__main__:main"
