name: Publish Release CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit message
      run: |
        commit_message="${{ github.event.head_commit.message }}"
        echo "$commit_message"
        echo "------"
        if [[ "$commit_message" =~ ([0-9]+\.[0-9]+\.[0-9]+) Release.+ ]]; then
          version="${BASH_REMATCH[1]}"
          echo "Version number: $version"
          # Use the captured version number for further processing
        else
          echo "Pattern doesn't match."
          exit 0
        fi

    - name: Checkout the code
      uses: actions/checkout@v2