name: Publish Release CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit message
      run: |
        commit_message="${{ github.event.head_commit.message }}"
        if [ $commit_message =~ \d+\.\d+\.\d+ Release.+ ]; then
          echo "Pattern matched."
          # ver=$(echo "$string" | grep -oP "^\d+\.\d+\.\d+ Release" | sed -E 's/ Release$//')
          # echo "$ver"
        else
          echo "Pattern doesn't match."
          exit 0
        fi

    - name: Checkout the code
      uses: actions/checkout@v2