name: Publish on release commit

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      status: ${{ steps.validate.outputs.status }}
      version: ${{ steps.validate.outputs.version }}

    steps:
    - id: validate
      name: Check commit message
      env:
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
      run: |
        echo "Commit message: $COMMIT_MESSAGE"
        regex="^([0-9]+\.[0-9]+\.[0-9]+) Release.*"
        if [[ $COMMIT_MESSAGE =~ $regex ]]; then 
          echo "Pattern matched."
          ver="${BASH_REMATCH[1]}"
          echo "Version: $ver"
          echo "status=success" >> $GITHUB_OUTPUT
          echo "version=$ver" >> $GITHUB_OUTPUT
        else
          echo "Pattern doesn't match."
          echo "status=fail" >> $GITHUB_OUTPUT
        fi

  work:
    needs: check
    if: needs.check.outputs.status == 'success'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Futher
      run: |
        echo "version: ${{ needs.check.outputs.version }}"