name: Run tests

on:
  push:
    branches:
      - '*'
    # paths:
    #   - 'mykit/**'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  on:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py_ver: ['3.10', '3.11']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: nvfp/turbotest@main
        with:
          python_ver: ${{ matrix.py_ver }}
          # dir: ./mykit
          dir: ./mykit/simplex  # temporarily: just test this
