name: Touch docs
on:
  push:
    branches:
      - main
    paths:
      - '_etc/docs/**'
  workflow_dispatch:
jobs:
  run:
    steps:
      - uses: nvfp/now-i-can-sleep@v5
        with:
          src: ./_etc/docs
          author: NVfastplease
          analytics: G-G3HERGXF6P
    runs-on: ubuntu-latest
    permissions: { pages: write, id-token: write }
