name: Build n publish to PYPI

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
    inputs:
      version:
        description: in `M.m.p(-...)?` format, like 1.0.0 or 3.1.4-b0 or 9.9.9-foo9
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install build twine
      - run: ls -la
      - run: python -m build
      - run: ls -la
      - run: ls -la ./dist
